### PR TITLE
Build updates

### PR DESCRIPTION
**Pull request by johnwillyn**
Changed package.json for latest react-ionic and other components and webpack.config.js for newer version.  Changed path reference for reactionic.sccs (which may not work with Meteor).

### CODE REVIEW

**Comment by pors** [comment]
@gabrielseco do you have a setup to test this PR?

**Comment by gabrielseco** [comment]
Right now, I don't have anything but I suppose I would clone his branch and test it in my computer https://github.com/johnwillyn/reactionic-kitchensink/tree/build-updates

If everything works with meteor and webpack, try to update the brewery example to see if it works too.

I will not be available  to review it until next Thursday.

**Comment by pors** [comment]
Great man!

**Comment by johnwillyn** [comment]
I did build this on 3 different Macs (all but one from scratch with webpack, etc.)

I also had a colleague test the webpack build on his machine.

I did not know there was a homebrew version.  Is that part of the kitchen sink demo app?

John

**Comment by pors** [comment]
@johnwillyn he is referring to the brewery example app: https://github.com/reactionic/brewery-app :)

**Comment by gabrielseco** [comment]
Tried today with meteor, all seems good, we have warnings because PropTypes and React.createClass but they were expected.

Tomorrow, I'll test with webpack and update the changes in a branch for the brewery app and I think this PR will be ready to merge

**Comment by johnwillyn** [comment]
Thanks. 

Apologies, I did not know about the Brewery app and  thought you were (somehow) referring to Homebrew on the Mac.

I glanced at it today, and the webpack config will probably need to be updated to things like adding ‘-loader’ on ‘babel’, etc.  Apparently these are required now.

I am looking into the PropTypes and createClass code migrations now.  It all seems pretty straightforward.

**Comment by gabrielseco** [comment]
Today, I looked into the webpack and all looks good to merge.

I looked into the brewery app and I think I never had the problem with webpack because I never used it before, I always used meteor.

I think @pors that we are ready to merge, do you want to do it and we close this PR.

**Comment by pors** [comment]
Thanks guys!

**Pull request merged**
